IBM/ibm-iam-operator

pkg/controller/securityonboarding/securityonboarding_controller.go
The pod stuck in initializing stage.
iam-onboarding-gnnft                               0/1     Init:1/5            0          82m
```
init-identity-provider:
Container ID:  
Image:         quay.io/opencloudio/icp-platform-auth:3.3.1
Image ID:      
Port:          <none>
Host Port:     <none>
Command:
sh
-c
until curl --cacert /certs/ca.crt -i -fsS https://platform-identity-provider:4300 | grep '200 OK'; do sleep 3; done;
State:          Waiting
Reason:       PodInitializing
Ready:          False
Restart Count:  0
Environment:    <none>
```
exec into the init-identity-provider container, run the curl command and found the error locating the /certs/ca.crt. Verify that that ca.crt file exists. Use openssl to view the cert, it does not recognize the format.
=> Workaround certissue

deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml, deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml, pkg/controller/authentication/configmap.go
This allows the user to only specify the prefix in new install
Here are the scenarios we handle-
**New install
1. user specifies none - we programatically enable roks with prefix set to empty string
2. user specifies roksPrefix - we programatically enable roks with prefix set to the one specified
3. user specifies roksURL, roksEnabled, and roksPrefix - we honor all
4. user specifies roksURL, roksEnabled - we set prefix to be IAM#, (to be consistent with previous release)
**Upgrade
we preserve existing settings on the cluster
=> Support changing only roks prefix

deploy/olm-catalog/ibm-iam-operator/3.7.4/ibm-iam-operator.v3.7.4.clusterserviceversion.yaml, deploy/operator.yaml
Updated latest sha digest for identity-manager operand image for CS 3.5.5 release.
=> Updated latest sha digest for identity-manager operand image for CS 3.5.5 release.

deploy/olm-catalog/ibm-iam-operator/3.7.5/ibm-iam-operator.v3.7.5.clusterserviceversion.yaml, deploy/operator.yaml, pkg/controller/authentication/configmap.go, pkg/controller/authentication/containers.go
Changed default value of OS_TOKEN_LENGTH to support OCP 4.6 in 3.7.4 branch (Issue #42278)
=> Changed default value of OS_TOKEN_LENGTH to support OCP 4.6 in 3.7.4 branch (Issue #42278)

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42505
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42565
```
docker manifest inspect registry.access.redhat.com/ubi8/ubi-minimal:8.3-201
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:5f931273a2b9250318a45914228c25e8e3ea0feec846edd67c92f03af1596a8a",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:c6592eb9cdd7ea7fa43beddf507ca2a8c2127f13ef66d49baea2fd28e37f62ba",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": …
```
=> update ubi images

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml, deploy/operator.yaml
Updated latest image sha digest for IAM operands.
Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41364
Travis multi-arch build links:
https://travis.ibm.com/IBMPrivateCloud/pap/jobs/41702797#L374
https://travis.ibm.com/IBMPrivateCloud/platform-auth-service/jobs/41702748#L299
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/41701316#L297
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/41701343#L313
=> Updated latest image sha digest for IAM operands.

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml, deploy/operator.yaml
Fixes issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42780
Travis multi-arch build link for image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/41895396#L317
=> Update operator.yaml to update sha for idmgmt

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml, deploy/operator.yaml
Updated latest image digest sha for IAM operand images.
Travis multi-arch build links for image digest sha:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43777242#L387
https://travis.ibm.com/IBMPrivateCloud/pap/jobs/43763998#L372	(Branch: release-3.3.9)
https://travis.ibm.com/IBMPrivateCloud/icp-iam-onboarding/jobs/43763701#L291	(Branch: release-3.3.8)
https://travis.ibm.com/IBMPrivateCloud/platform-auth-service/jobs/43764274#L297	  (Branch: release-3.3.12)
=> Updated latest image digest sha for IAM operand images.

deploy/crds/iam.policies_v1alpha1_iampolicy.yaml, deploy/crds/oidc_v1_client_crd.yaml, deploy/crds/operator.ibm.com_authentications_crd.yaml, deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml, deploy/crds/operator.ibm.com_paps_crd.yaml, deploy/crds/operator.ibm.com_policycontrollers_crd.yaml, deploy/crds/operator.ibm.com_policydecisions_crd.yaml, deploy/crds/operator.ibm.com_secretwatchers_crd.yaml, deploy/crds/operator.ibm.com_securityonboardings_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/iam.policies_v1alpha1_iampolicy.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/oidc_v1_client_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_authentications_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_oidcclientwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_paps_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policycontrollers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policydecisions_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_secretwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_securityonboardings_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/iam.policies_v1alpha1_iampolicy.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/oidc_v1_client_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_authentications_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_oidcclientwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_paps_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policycontrollers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policydecisions_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_secretwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_securityonboardings_crd.yaml
Addresses content linter tool that flags the CRDs for not having labels. Part of the effort of reducing the number of lintOverrides required. 
See: https://ibm-cloudplatform.slack.com/archives/G013X1K33AN/p1605882743123300
```
[INFO] deploy/crds/iam.policies_v1alpha1_iampolicy.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels (RequiredMetadataLabelsDefined)
[INFO] deploy/crds/oidc_v1_client_crd.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels (RequiredMetadataLabelsDefined)
[INFO] deploy/crds/operator.ibm.com_authentications_crd.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined …
```
=> adding metadata labels to crds to address certification linter rules

deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml, deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml, deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml, deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml, deploy/operator.yaml
Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44140
=> Issue44140 - update audit syslog image to version 1.0.5

Makefile
Update Makefile to use v1.0.3 version manifest tool for 3.8 EUS branch.
=> Update Makefile to use v1.0.3 version manifest tool for 3.8 EUS branch.

pkg/controller/policydecision/containers.go
Added IDENTITY_MGMT_URL to auth-pdp container. (Issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44579)
=> Added IDENTITY_MGMT_URL to auth-pdp container. (Issue #44579)

pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/webhook.go, pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go, pkg/controller/pap/containers.go, pkg/controller/policydecision/containers.go
- Changed name of `namespace-admission-config` webhook to include namespace to differentiate across multiple instances of IAM. (Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45715)
- Added `IBM_CLOUD_SAAS` env variable to pdp, pap and oidcclient-watcher containers. (Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45717)
=> Changed name of namespace-admission-config webhook to support SAAS

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46750
docker manifest inspect registry.access.redhat.com/ubi8/ubi-minimal:8.3-298.1618432845
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:a62d408337bb50546019e2334fdd43ec1ecc150d60f5f195fd324c578c25ab3a",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:231d86e11434aeace9f879006fbba111ce4cf03db6441fd43e172e4c7212606c",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737, …
=> Update Dockerfile - update Ubi images for 3.6.5

pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/webhook.go, pkg/controller/securityonboarding/securityonboarding_controller.go
Code changes handle namespace-admission-config webhook resource on upgrade (Issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46960)
Added IBM_CLOUD_SAAS env varaible to iam-onboarding job. (Issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46959)
=> Code changes handle namespace-admission-config webhook resource on upgrade (Issue #46959)

deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml, deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml, deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml, deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_policycontrollers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_secretwatchers_crd.yaml, deploy/role.yaml
- Updated csv, crds and crs with new config parameter `excludeOperand` for secret-watcher and policy-controller. (Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47094)
- Updated csv with other missing config parameters.
=> Updated csv, crds and crs with new config parameter excludeOperand for secret-watcher and policy-controller.

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x
Update to latest to remediate CVE-2021-27219 package glib2
=> Update Dockerfile - to latest ubi 8

pkg/controller/authentication/webhook.go
Seeing this error in kube-apiserver and consistently failing test case.
```
W0712 15:28:05.490458      19 dispatcher.go:170] Failed calling webhook, failing open iam.hooks.securityenforcement.admission.cloud.ibm.com: failed calling webhook "iam.hooks.securityenforcement.admission.cloud.ibm.com": converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
E0712 15:28:05.490484      19 dispatcher.go:171] failed calling webhook "iam.hooks.securityenforcement.admission.cloud.ibm.com": converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
W0712 15:28:05.681344      19 dispatcher.go:170] Failed calling webhook, failing open iam.hooks.securityenforcement.admission.cloud.ibm.com: failed calling webhook …
```
=> add v1beta - web hook conversion error

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml, deploy/operator.yaml
Fixes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48416
updated images from:
```
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:48a4bec3d1dec90b5dd5420bf7c41a5756b7fbe8b862546134fbe2caa607679f",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:ad1de47449386ae0f6009c38d714cbcc218d6f8087ea2d45272b671baa5072af",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": …
```
=> Update operator.yaml to bump up operands and move to latest ubi

deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml, deploy/operator.yaml
Bump up identity manager version to 3.6.1 after build passes for August release.
=> Update operator.yaml to bump identity manager after build passes

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml, deploy/operator.yaml
Move to latest ubi-minimal:8.4-205.1626828526
docker manifest inspect registry.access.redhat.com/ubi8/ubi-minimal:8.4-205.1626828526
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:7735715721f161dea5603092c040b5eb89ab101044617f67288a866d0f9d0aaa",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:3fd316744d34570518af714b729fc6d744a7860af5e25594f1b48f315d59419a",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": …
=> Update Dockerfile to move to latest ubi minimal and latest audit 1.0.8

pkg/controller/authentication/webhook.go
Reverts IBM/ibm-iam-operator#407
=> Revert "Update webhook.go" to use v1beta1

Makefile, common/scripts/lint-csv.sh, common/scripts/next-csv.sh, deploy/olm-catalog/ibm-iam-operator/3.12.0/iam.policies_v1alpha1_iampolicy.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/ibm-iam-operator.v3.12.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/oidc_v1_client_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_authentications_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_oidcclientwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_paps_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_policycontrollers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_policydecisions_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_secretwatchers_crd.yaml, deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_securityonboardings_crd.yaml, deploy/operator.yaml, version/version.go
update next-csv.sh to:
1.support manually enter new-version and prev-version, therefore support bump up version x/y
if new-version not manually provided, will use the current logic to bump up version z by 1
2.fix missing " in several commands
bump up version from 3.11.2 to 3.12.0
=> update next-csv.sh bump up version to 3.12.0 for CS 3.12

pkg/controller/authentication/webhook.go
Reverts IBM/ibm-iam-operator#421
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49888
=> Revert "Update webhook.go" to remove new cert annotation

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml, deploy/operator.yaml
operand versions at 3.10.0 level except for platform-identity-manager and provider which contain most of the changes.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55512
=> [Cloudpak 3.0] - Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

Makefile, pkg/apis/oidc/v1/client_types.go, pkg/controller/client/client_controller.go, pkg/controller/client/client_controller_config.go, pkg/controller/client/clientreg.go, pkg/controller/client/iam.go, pkg/controller/client/icperror.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55959
- Change all of the Client controller's direct interactions with the OP
to route through the identity provider endpoints instead
- Provide the ability to use the cpclient_credentials grant type, which
replaces the use of service ID tokens. This grant type is available
whenever a Client CR has the following fields set:
1. `zenAuditUrl`, which represents the URL of the Zen Audit service
that usage is reported to, and
2. `roles`, which is a list of strings that map to
`functional_user_groupIds` in the OP.
- Update logging to more uniformly utilize the controller-runtime's
logger for consistency.
=> Enable cpclient_credentials grant type

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Update to map the content of OperatorGroup and namespace-scope ConfigMap within the namespace it is deployed, to provide the backwards-compatibility for the contributed services which rely on the NSS interface for getting a list of watched namespaces.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56808
=> Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to read from namespace scope

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to remove cert-manager dependency:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56784
=> Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to remove cert-manager dependency

pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/certificate.go
do not watch v1alpha certificates on CP3
=>  [CP3.0] - Update authentication_controller.go to fix calls to v1alpha certs

pkg/controller/authentication/routes.go
Originating issue: [IBMPrivateCloud/roadmap#57284](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57284)
- Fixes nil pointer dereference when trying to log out Route comparisons in reconcile loop
=> Add nil checks to IsRouteEqual logging

deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml, pkg/apis/operator/v1alpha1/authentication_types.go, pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/resourcestatus.go
Originating issue: [IBMPrivateCloud/roadmap#56761](https://github.ibm.com/ibmprivatecloud/roadmap/issues/56761)
- Add service block to Authentication status that reports a red/green status of each of the Authentication's owned resources; meant to be consumed by ODLM.
=> Add ODLM service status to Authentications

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml, pkg/apis/operator/v1alpha1/authentication_types.go, pkg/controller/authentication/authentication_controller.go
Originating Issues:
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57006
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57372
- Reintroduce `auditService` property to the `Authentication` CR/CRD in order to avoid breaking Common Services 3.x installs in scenarios where Common Services 2.x is installed after it.
- Set dummy data within the `auditService` to make it clear that the fields should be ignored in Common Services 3.x given they do not map back to any meaningful changes in behavior.
=> Undo audit service spec removal and add dummy data

pkg/apis/addtoscheme_oidc_v1.go, pkg/controller/client/client_controller.go, pkg/controller/client/client_controller_config.go, pkg/controller/client/clientreg.go, pkg/controller/client/iam.go
Addresses the following:
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57489
- https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57490
Changes:
- Perform an intelligent guess on where the shared services namespace is based upon where the Operator is able to list an Authentication CR. There should only ever be one present among the namespaces the Operator can list. If no or more than one Authentication CR is found, an error is thrown as this is an unsupported usage of the Authentication CR.
- Use the shared services namespace for lookups of ConfigMaps, Secrets, etc.
- Revert use of namespace-to-ClientControllerConfig map to just a single ClientControllerConfig on ReconcileClient because the resources being looked up should always be in the shared services namespace, thus no …
=> Derive shared services namespace from Authentication

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
In latest CSV update, operator image was updated to point at our operand location (`icr.io/cpopen/cpfs` instead of the operator location `icr.io/cpopen`).
=> Fix operator reference in CSV

pkg/controller/authentication/service.go
Handle update for both `label` and `podselector` during the CP3 upgrade for the below services :
```
platform-auth-service,
platform-identity-management,
platform-identity-provider
```
Operator logs -
```
{"level":"info","ts":1678972184.4709521,"logger":"controller_authentication","msg":"Upgrade check : Successfully updated service podSelector , label details ","Instance.Namespace":"ibm-common-services","Instance.Name":"example-authentication","Service.Name":"platform-auth-service"}
{"level":"info","ts":1678972184.4709523,"logger":"controller_authentication","msg":"Upgrade check : Successfully updated service podSelector , label details ","Instance.Namespace":"ibm-common-services","Instance.Name":"example-authentication","Service.Name":"platform-identity-provider"} …
```
=> Service Upgrade handling for IM4.0 

pkg/controller/authentication/sacc.go, pkg/controller/client/client_controller.go, pkg/controller/common/resources.go
When updating operand Service account with annotations for Client CR scenario, namespace need to be the one where IAM operand is running
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58410
=> fix SA update for clients

pkg/apis/addtoscheme_operator_v1alpha1.go, pkg/apis/utils.go, pkg/controller/client/clientreg.go
Originating issue: [IBMPrivateCloud/roadmap#58413](https://github.ibm.com/ibmprivatecloud/roadmap/issues/58413)
Previously, whether or not to add the Route schema to the Manager was determined by values set within the ibm-cpp-config ConfigMap that indicated whether the cluster was OpenShift or CNCF. This approach was vulnerable to timing issues that led to the Operator Pod repeatedly crashing until the ConfigMap was made available.
Now, the code attempts to list Routes; if the error relates to the Routes API not being registered on the cluster, then loading the scheme will be skipped.
=> Fix registered API detection

pkg/controller/authentication/containers.go
Invoking JMX API from provider is causing oauthadmin related errors in Liberty.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58437
In some cases that is preventing client registration from succeeding using oauthadmin
=> Update containers.go to remove JMX API check

pkg/controller/client/client_controller.go, pkg/controller/client/clientreg.go
- Removes unneeded logic surrounding caching of certificate Secret and replaces with a plain getter.
=> Simplify Client reconciler cert usage

pkg/controller/authentication/routes.go
Originating issue: [IBMPrivateCloud/roadmap#58513](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58513)
As part of authorization flow in OIDC, a state parameter is set to track requests and defend against CSRF. When Common Services was using IBM management ingress, it could define various nginx customizations within annotations on its Ingress objects such as rewriting targets or even scripted behaviors. Among other things, the IAM Operator's Ingress for platform-login had been customized to generate a timestamp and submit that as the `state` parameter for inbound authorize requests.
When Common Services moved away from using management ingress in favor of using OpenShift Routes and the default OpenShift Router, it meant that many of these customizations needed to be reevaluated …
=> Remove `state` parameter from platform-login Route

pkg/controller/authentication/configmap.go
```
data:
cluster_address: cp-console-ibm-common-services.ujjwal-roks-4-fae6c235d7a3aed6346697c0e75f4896-0000.jp-tok.containers.appdomain.cloud
cluster_endpoint: https://cp-console-ibm-common-services.ujjwal-roks-4-fae6c235d7a3aed6346697c0e75f4896-0000.jp-tok.containers.appdomain.cloud
cluster_kube_apiserver_host: c103-e.jp-tok.containers.cloud.ibm.com
cluster_kube_apiserver_port: "30579"
cluster_name: mycluster
cluster_router_http_port: "80"
cluster_router_https_port: "443"
im_idmgmt_endpoint: https://platform-identity-management.ibm-common-services.svc:443
im_idprovider_endpoint: https://platform-identity-provider.ibm-common-services.svc:4300
proxy_address: cp-proxy-ibm-common-services.ujjwal-roks-4-fae6c235d7a3aed6346697c0e75f4896-0000.jp-tok.containers.appdomain.cloud
kind: ConfigMap …
```
=> update https for cluster ep

pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/configmap.go, pkg/controller/authentication/constants.go
Originating issue: [IBMPrivateCloud/roadmap#58510](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58510)
- Update the registration-json ConfigMap on each reconcile loop instead of only creating the ConfigMap if it doesn't already exist.
- Reorder handlers so ConfigMap handling runs after Secret handling.
- Convert registration-json JSON generation to use Go template instead of string replacement.
- Refactor redirect URI-related code for clarity.
=> Update registration-json to reconcile regularly

pkg/controller/authentication/authentication_controller.go, pkg/controller/authentication/configmap.go, pkg/controller/authentication/job.go, pkg/controller/authentication/resourcestatus.go, pkg/controller/authentication/secret.go, pkg/controller/client/client_controller.go, pkg/controller/client/clientreg.go, pkg/controller/common/resources.go
Originating issue: [IBMPrivateCloud/roadmap#58841](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58841)
During backup and restore, the ibmcloud-cluster-info ConfigMap and the ibmcloud-cluster-ca-cert Secret would block the IM Operator from coming completely online because it expects that it owns those resources; however, when the resources were restored, the ownerReferences were not also restored. This fix to the IM Operator attempts to assert controller status on behalf of the Authentication CR upon the ibmcloud-cluster-info ConfigMap when it isn't controlled by that Authentication CR, and, in the case of ibmcloud-cluster-ca-cert, the IM Operator will simply delete the Secret and create a new one to replace it.
=> Fix ownership of ibmcloud-* resources issues

go.mod, go.sum
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59394
=> Updated go-restful to v3.8.0

pkg/controller/authentication/ingress.go
Fixes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59023
set header X-Content-Type-options to nosniff for paths '/idauth' and '/oidc/endpoint'
=> Dynamic scan - set X-Content-Type-options to nosniff

pkg/controller/authentication/ingress.go
Fix: [#59730](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59730)
Affected url : [/idauth/oidc/endpoint/OP/registration](https://cp-console.apps.sober.cp.fyre.ibm.com/idauth/oidc/endpoint/OP/registration)
set content-type to nosniff for **/idauth/oidc**
=> dynamic scan - x-content-type header set to nosniff

base_images.json, pkg/controller/authentication/ingress.go
Fix: [#59848](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59848)
Fix to dynamic scan seeing medium and low sev issue
Medium - CSP header not set
Low - Strict-Transport-Security Header Not Set
=> Dynamic scan ltsr - headers not set 

pkg/controller/authentication/ingress.go
Added X-Content Type Options Header to `/iam-token`
dynamic scan fix: [#60529](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60529)
=> Added X-Content Type Options Header

README.md, common/scripts/.githooks/pre-commit
This is a change to trigger the post-merge CICD webhook and should be reverted once done.
=> Trigger build to revert

Makefile, build/Dockerfile.amd64, build/Dockerfile.ppc64le, build/Dockerfile.s390x
Originating issue: [IBMPrivateCloud/roadmap#61811](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61811)
The Makefile was using the wrong build argument to pass the `GOARCH` value to the compiler for the manager. This resulted in the desired value not being properly set for image builds, which then led to the binaries only being compiled for Linux on whatever the host architecture happened to be.
Given there are already separate Dockerfiles for each architecture the project supports, the Dockerfiles no longer take this build argument and, instead, the build stage in each file explicitly states the desired `GOARCH` value.
=> Fix Dockerfile arch compile target

controllers/operator/authentication_controller.go
Originating issue: [IBMPrivateCloud/roadmap#61879](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61879)
* Remove shadowing of the `err` variable within the deferred function that updates the Authentication CR status
=> Fix shadowing of err in Authentication controller

controllers/operator/authentication_controller.go, controllers/operator/operandrequest.go
More requeues happening in the Operator's controllers leads to an increased propensity to hit exponential backoff. Given the Authentication controller only manages a single CR instance, the reconciliation logic can afford to provide more explicit, quick turnarounds for loops without having to worry too much about the impact on the overall rate limit.
=> Add delays to Authentication requeues

migration/schema/v1/tables.go, migration/schema/v1/tables_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62716
Background on the issue: Initially we thought that `id` field from Directory need to considered as uid. but this seems to be wrong. so when a directory is onboarded, the get call returns below response which has `_id` and this has to be considered as uid
```
{
"_id" : "64257460-e65c-11ee-bc9f-afdf81dc128f",
"LDAP_ID" : "sert-openldap",
"LDAP_REALM" : "REALM",
"LDAP_HOST" : "XXXXXXXXXX",
"LDAP_PORT" : "389",
"LDAP_IGNORECASE" : "false",
"LDAP_BASEDN" : "BASEDNVALUE",
"LDAP_BINDDN" : "BINDDNVALUE",
"LDAP_BINDPASSWORD" : "PASSWORD",
"LDAP_TYPE" : "Custom",
"LDAP_USERFILTER" : "(&(uid=%v)(objectclass=person))",
"LDAP_GROUPFILTER" : "(&(cn=%v)(objectclass=groupOfUniqueNames))",
"LDAP_USERIDMAP" : "*:uid",
"LDAP_GROUPIDMAP" : "*:cn", …
```
=> assign directory's _id to uid

Makefile
Additionally
* Fix `fmt` target so that it no longer uses a hard-coded version value for the Go sdk path.
=> Update Go 1.21.7 -> 1.21.8

migration/migration.go, migration/schema/v1/tables.go, migration/schema/v1/tables_test.go
Originating issue: [IBMPrivateCloud/roadmap#62770](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62770)
* Query Team collection in MongoDB to determine initial role value for User rows
=> Update Non Zen User roles for isolated upgrade

controllers/common/constants.go, controllers/oidc.security/client_controller.go
Originating issue: [IBMPrivateCloud/roadmap#62692](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62692)
* Check for `platform-identity-provider` Deployment availability before attempting OIDC registration
* Check for `platform-identity-management` Deployment availability before attempting Zen registration
* Cluster subreconciler definitions together and in order of execution
=> Check for Deployments before registering Clients

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml, controllers/operator/authentication_controller.go, controllers/operator/clusterrolebinding.go
Originating issue: [PrivateCloud-analytics/CPD-Quality#18726](https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/18726)
* Support multiple IM Operator instances by creating unique ClusterRoleBindings for each Authentication instance.
=>  Create unique ClusterRoleBindings

apis/operator/v1alpha1/authentication_types.go, controllers/operator/authentication_controller.go, controllers/operator/resourcestatus.go, migration/migration.go
Originating issue: [IBMPrivateCloud/roadmap#62506](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62506)
* Add the MigrationsPerformed condition to the Authentication CR, which communicates whether all necessary migrations have been performed. This status factors into the `.status.service` that the Authentication reports - when one or more migrations are active or have failed, the Authentication is flagged as NotReady.
=> Add MigrationsPerformed condition

migration/migration.go, migration/schema/v1/tables.go
Related to issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62772
Migration of SCIM JIT data from Mongo to EDB:
- Copies existing data from "Groups" Mongo collection into related EDB tables
- Creates mapping of user and group in relevant EDB tables from existing "members" field data in Groups collection
=> Scim Jit Data Migration

migration/schema/v1/tables.go
Related to issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62845
Summary of changes:
- Fetching "uid" of user based on "realm_id" OR "type" column for users_groups mapping during migration of scim-jit data
=> Fetching "uid" of user based on "realm_id" OR "type" column

migration/migration.go
Summary of changes:
1. Fixing bug where nil was being returned if a user already existed in the users table in EDB, causing nil pointer errors in further flows.
=> Issue-63379: Fix for nil pointer error if user has already been migrated

controllers/operator/configmap.go
post backup and restore, this ensures ROKS_URL in platform-auth-idp configmap is updated with right url incase post backup and restore ROKS_URL holds the old cluster url
Ref: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62929
=> ensure roks_url is correct

controllers/operator/authentication_controller.go, controllers/operator/certificate.go, go.mod, go.sum, main.go
CVE-2024-36537 - `github.com/cert-Manager/cert-manager` reports a high sev vulnerability which states that Insecure permissions in cert-manager v1.14.4 allows attackers to access sensitive data and escalate privileges by obtaining the service account's token. Resolution would be to change the reference to CRs from CS cert-manager rather than jetstack which was followed by ibm-commonui-operator priorly.
Fix - https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64509
=> use cert apis from ibm cert mgr operator

controllers/operator/containers.go
introduce 30s delay once after init container check the basic TCP probe. This is to ensure add buffer time for liberty to connect with the running EDB instance.
=> sleep introduce for init container

Dockerfile, Makefile
Addressing Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64328
=> Updating go version from 1.21.8 to 1.21.9

controllers/operator/ingress.go, controllers/operator/resourcestatus.go, controllers/operator/routes.go, controllers/operator/routes_test.go, controllers/operator/zenextension.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61141
Parent issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60011
The redundant endpoint "\idauth" is not needed as it redirects to the next endpoint in the route. Therefore, causing an increase in number of security issues.
=> Clear redundant enpoint idauth

controllers/operator/operandrequest_test.go, controllers/operator/routes_test.go, testing/utils.go
* Add tests for Route handling behavior when ZenExtension for front door has different combinations of status state.
* Move common testing functions into their own testing package
=> Add tests for Route handling with front door

controllers/operator/ingress.go, controllers/operator/resourcestatus.go, controllers/operator/routes.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61141
Parent issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60011
The redundant endpoint "\idauth" is not needed as it redirects to the next endpoint in the route. Therefore, causing an increase in number of security issues.
=> [SC2] Remove idauth route

apis/operator/v1alpha1/authentication_types.go, controllers/common/utils.go, controllers/oidc.security/client_controller.go, controllers/operator/routes.go, migration/migration.go
Originating issue: [IBMPrivateCloud/roadmap#64896](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64896)
When ZenInstance documents are broken, e.g. the OIDC clients referred to by them no longer exist, they break migration. Whenever this happens, instead skip these documents as well as ZenInstanceUser documents that refer to the skipped ZenInstance.
Additionally, introduce a subreconciler to the Client controller to wait for the Authentication CR to become ready before attempting to manage OIDC client registrations.
=> Skip migrating broken Zen documents

Makefile
Originating issue: [IBMPrivateCloud/roadmap#64971](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64971)
Enables BuildKit so that systems using Docker for image builds will build images for other architectures correctly.
(cherry picked from commit 7cf9363172e0d252e66f7bc3d1ba311edc7a7905)
=> Add BuildKit variable to image builds

controllers/operator/ingress.go, controllers/operator/resourcestatus.go, controllers/operator/routes.go
As 4.6.x stream is a patch release, This will break the existing customers running in previous versions of 4.6.x release as it will get automatically upgraded to Bedrock 4.6.8. Therefore, this change should not go in for 4.6.x release.
=> [SC2]Revert idauth removal

controllers/operator/authentication_controller.go
Originating issue: [IBMPrivateCloud/roadmap#64955](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64955)
When attempting to override whether the migration should be considered complete or not, e.g. setting `"authentication.operator.ibm.com/migration-complete"` to `"true"` when some migration failure has resulted in some non-essential data never reaching EDB, it could get the Authentication stuck in an InProgress state.
This adds a subreconciler that ensures that, upon exiting the migration subreconciler, the Authentication CR always has the MigrationsPerformed condition set to True.
=> Ensure MigrationsPerformed is True when done migrating

controllers/operator/ingress.go, controllers/operator/resourcestatus.go, controllers/operator/routes.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61141
Parent issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60011
The redundant endpoint "\idauth" is not needed as it redirects to the next endpoint in the route. Therefore, causing an increase in number of security issues.
=> [SC2] Clear redundant endpoint idauth

Makefile, controllers/oidc.security/client_controller.go, controllers/oidc.security/clientreg.go, controllers/oidc.security/zen_registration.go
Originating issue: [IBMPrivateCloud/roadmap#65093](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65093)
After the Operator SDK upgrade, watching the Client-owned Secrets was no longer enabled. This adds that behavior back in.
Additionally:
* Use common target for building platform images
* Add missing error handling
=> [CD] Enable Client controller watch of Client Secrets

Makefile, controllers/oidc.security/client_controller.go, controllers/oidc.security/clientreg.go, controllers/oidc.security/zen_registration.go
Originating issue: [IBMPrivateCloud/roadmap#65093](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65093)
After the Operator SDK upgrade, watching the Client-owned Secrets was no longer enabled. This adds that behavior back in.
Additionally:
* Use common target for building platform images
* Add missing error handling
(cherry picked from commit 7eace55e678a5825fe71b93c389de876c51bf974)
=> [SC2] Enable Client controller watch of Client Secrets

controllers/operator/authentication_controller.go
Originating issue: [PrivateCloud-analytics/Zen#39543](https://github.ibm.com/PrivateCloud-analytics/Zen/issues/39543)
If Zen and IM were installed on the cluster at the same time, and the Zen front door was enabled on the Authentication CR, this would lead to IM waiting for the ZenExtension resource to be reconciled without standing up its Operands for Zen to register OIDC clients with.
This changes the order in which objects are reconciled so that Zen will be able to communicate with IM's Operands and create those OIDC clients, which will in turn allow the Zen Operator to handle the ZenExtensions that IM needs in order to expose its Operands to ingress traffic.
=> Reconcile Routes and ZenExtension later

apis/operator/v1alpha1/authentication_types.go, controllers/common/constants.go, controllers/operator/authentication_controller.go, controllers/operator/configmap.go, controllers/operator/configmap_test.go
Originating issue: [IBMPrivateCloud/roadmap#65249](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65249)
* Always determine the correct ROKS_URL value instead of assuming the contents of the ConfigMap are already correct.
* Refactor ConfigMap handling so that it conforms to subreconciler pattern and otherwise tidy the logic of this part of the Authentication controller.
=> Always update ROKS_URL in platform-auth-idp

controllers/operator/configmap.go, controllers/operator/configmap_test.go
Originating issue: [IBMPrivateCloud/roadmap#65604](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65604)
* Add a check to be sure that, if a selected key is not present in the observed ConfigMap that is present in the generated one, the selected key is added to the observed ConfigMap.
* Always update DEFAULT_LOGIN to whatever is set in the Authentication CR.
* Update test to account for this change.
=> Always update values in platform-auth-idp when triggered

apis/oidc.security/v1/groupversion_info.go, controllers/common/resources.go, controllers/common/utils.go, controllers/operator/authentication_controller.go, controllers/operator/configmap.go, controllers/operator/migration.go, controllers/operator/secret.go, database/connectors/options.go, main.go
Originating issue: [IBMPrivateCloud/roadmap#64854](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64854)
* Set InsecureSkipVerify to false
* Replace Certificate type import with copied types from cert-manager
* Add unit tests around Certificate reconciliation
* Modify MongoDB bootstrap script contents to create internal certificate including Service FQDN
=> [SC2] Enable SSL verification on MongoDB migrations

Dockerfile, Makefile
Originating issue: [IBMPrivateCloud/roadmap#65705](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65705)
* Place LICENSE in /licenses
* Add RH image labels
=> [CD] Update image builds for RH Certification

Makefile, go.mod
Addresses [GO-2025-3420](https://pkg.go.dev/vuln/GO-2025-3420) and [GO-2025-3373](https://pkg.go.dev/vuln/GO-2025-3373)
=> [CD] Upgrade go version to 1.23.5

controllers/operator/configmap.go, controllers/operator/configmap_test.go
The `ibmcloud-cluster-info` ConfigMap is now reconciled as follows:
* If the `cluster_address_auth` field is not present in either case (e.g. upgrade from IM version without this field), it is set to match the `cluster_address` field's value.
* If the Zen front door is disabled, the ConfigMap is initially created with the default cp-console values and is left unmanaged after that point.
* If the Zen front door is enabled, all hostname values for `cluster_address`, `cluster_address_auth`, `cluster_endpoint`, and `proxy_address` are aligned to match the hostname provided by Zen.
=> Rework ibmcloud-cluster-info reconcile

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/operator/authentication_controller.go, controllers/operator/clusterrole.go, controllers/operator/clusterrolebinding.go, controllers/operator/configmap.go
* Remove 'https://' from API server IP
* Fix failing SSARs
=> Miscellaneous bug fixes

Makefile, go.mod
Addresses [GO-2025-3420](https://pkg.go.dev/vuln/GO-2025-3420) and [GO-2025-3373](https://pkg.go.dev/vuln/GO-2025-3373)
=> [SC2] Upgrade go version to 1.23.5

helm/templates/00-rbac.yaml
Adding missing RBAC for Helm chart that was previously added to CSV in order to comply with RH certification guidelines.
=> Add operandbindinfo permissions to chart role

helm-cluster-scoped/templates/10_clusterrole.yaml, helm-cluster-scoped/templates/11_clusterrolebinding.yaml
Originating issue: [IBMPrivateCloud/roadmap#65980](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65980)
Append namespace to ClusterRole and ClusterRoleBinding names to make them unique in multi-tenant use cases.
=> Multi-tenancy with cluster charts

helm/templates/10-deployment.yaml
I think this line is causing a problem in the iam helm chart:
> Error: INSTALLATION FAILED: parse error at (ibm-iam-operator/templates/10-deployment.yaml:270): unexpected {{end}}
I don't see an equivalent line in the cs operator https://github.com/IBM/ibm-common-service-operator/blob/master/helm/templates/operator-deployment.yaml#L57 or an unclosed if condition before this {{end}}
=> extra {{end}} causing problems with deployment of latest iam chart

helm/templates/10-deployment.yaml
For the same reason we updated the operator imagePullPrefix to take different values, we need to update the operand image locations. This is primarily a factor in test cases where dev images are stored in different repos (like EDB, CPD, and CPFS images all being in different places). This prevents us from needing multiple different top overrides files.
=> update image pull prefix for operands

go.mod, go.sum
Issue - https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66131
CVE-2025-22870 of medium sev states that `In Go net/http, x/net/proxy, x/net/http/httpproxy there is a proxy bypass vulnerability using IPv6 zone IDs. Matching of hosts against proxy patterns could improperly treat an IPv6 zone ID
as a hostname component. For example, when the NO_PROXY environment variable was
set to "*.example.com", a request to "[::1%25.example.com]:80 would incorrectly
match and not be proxied. This affects versions before 1.23.7 and 1.24.x before 1.24.1.` The suggested fix is to move to v0.36.0
=> [SC2] Update golang.org/x/net to v0.36.0

controllers/oidc.security/client_controller.go, controllers/oidc.security/client_controller_config.go, controllers/operator/authentication_controller.go, controllers/operator/certificate_test.go, controllers/operator/configmap.go, controllers/operator/configmap_test.go, controllers/operator/operandbindinfo_test.go, controllers/operator/operandrequest_test.go, controllers/operator/routes_test.go, controllers/operator/secret.go, main.go
Originating issue: [IBMPrivateCloud/roadmap#66250](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66250)
Fall back to querying the API server directly when an object isn't found just in case the cache filtering is leading to missing existing objects.
=> Get from API server when cache fails

controllers/operator/configmap.go
Log.Info expects key value pairs, else throws errors. We don't want these errors in our logs that deviate us from the real issue.
=> add key value pairs to log statements

controllers/operator/routes.go
Originating issue: [IBMPrivateCloud/roadmap#66287](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66287)
* Fall back to checking API server for Secrets during Route reconcile
=> Try reading from API server for Route Secrets

internal/controller/operator/configmap.go, internal/controller/operator/configmap_test.go, internal/controller/operator/containers.go
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66941
Requirement : Additional attribute like "email" , "username" should be propagated to the JIT group members section for the CPD to display this .
Design discussion:
Use a similar approach of having a flag like the ATTR_MAPPING_FROM_CONFIG in platform-auth-idp cm which when enabled would send the additional attributes - email and username fro JIT Groups. This would ensure that the standards for JIT is maintained and would not cause any backward compatibility issues.
Therefore, in order to have these attributes --> the customer would need to enable the flag in the cm. Once enabled, the additional fields would be sent in the GET SCIM Group response allowing the fields to be populated in the UI.
=> Add flag to enable extra attribute for JIT

controllers/operator/containers.go
This is to have separate probes for auth-svc.
```
sh-4.4$ curl -kL https://platform-auth-service.common-services.svc.cluster.local:9443/oidc/endpoint/OP/jwk
{"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"xxxxx"}]}
```
=> update liveness probe from authsvc

api/operator/v1alpha1/authentication_types.go, bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml, config/rbac/role.yaml, helm/templates/00-rbac.yaml, helm/templates/10-deployment.yaml, helm/values.yaml, internal/controller/common/secondary.go, internal/controller/operator/authentication_controller.go, internal/controller/operator/configmap.go, internal/controller/operator/constants.go, internal/controller/operator/job.go, internal/controller/operator/migration.go, internal/controller/operator/operandrequest.go, internal/controller/operator/resourcestatus.go, internal/controller/operator/resourcestatus_test.go
* Some Job name checks were using the wrong name or gates; now using a single constant to ensure the same value is used or otherwise corrected those gates
* Introduce a requeue if the Cluster CR is not ready to prevent the database-related Jobs from running to failure
* Permissions were too stringent on mounted volumes in Jobs; added group write
=> Fix miscellaneous bugs

helm-cluster-scoped/templates/00_operator.ibm.com_authentications.yaml, helm-cluster-scoped/templates/01_oidc.security.ibm.com_clients.yaml, helm-cluster-scoped/templates/10_clusterrole.yaml, helm-cluster-scoped/templates/11_clusterrolebinding.yaml
What this PR does / why we need it: CPD BR team requires cluster scoped resources to have both addOnID and tenant operator namespace defined in all cluster resources so they can be appropriately tracked and backed up. Enabling these values allows for flexibly setting both common labels for namespace scoped and cluster scoped resources and cluster specific labels.
Which issue(s) this PR fixes:
Fixes # https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/57014
=> CPD-Quality 57014, add default labels to cluster scoped resources

internal/controller/bootstrap/authentication_bootstrap_controller.go, internal/controller/oidc.security/client_controller.go, internal/controller/operator/authentication_controller.go, internal/controller/operator/certificate.go, internal/controller/operator/client.go, internal/controller/operator/clusterrole.go, internal/controller/operator/clusterrolebinding.go, internal/controller/operator/configmap.go, internal/controller/operator/deployment.go, internal/controller/operator/hpa.go, internal/controller/operator/ingress.go, internal/controller/operator/job.go, internal/controller/operator/migration.go, internal/controller/operator/operandbindinfo.go, internal/controller/operator/operandrequest.go, internal/controller/operator/resourcestatus.go, internal/controller/operator/resourcestatus_test.go, internal/controller/operator/role.go, internal/controller/operator/rolebinding.go, internal/controller/operator/routes.go, internal/controller/operator/sacc.go, internal/controller/operator/secret.go, internal/controller/operator/service.go, internal/controller/operator/zenextension.go
* Further divided logging to be more terse by default
* Fixed an issue where wait for Cluster CR would block when configured to use external EDB
=> Logging overhaul, part 2

helm-cluster-scoped/templates/00_operator.ibm.com_authentications.yaml, helm-cluster-scoped/templates/01_oidc.security.ibm.com_clients.yaml, helm-cluster-scoped/templates/10_clusterrole.yaml, helm-cluster-scoped/templates/11_clusterrolebinding.yaml, helm/templates/00-rbac.yaml, helm/templates/10-deployment.yaml
See https://github.com/IBM/ibm-common-service-operator/pull/2636
essentially, the CPD team has trouble with the helm charts when the labels fields are not defined so making them conditional should side step this problem
=> update labeling to make them conditional

internal/controller/operator/job.go
Allows migrated_to_* writes back to mongodb to use correct key within migrator Job.
=> Add POD_NAMESPACE to migrator Job

internal/controller/oidc.security/zen_registration.go
FIxes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67950
when we have value that of type []byte, json.Marshal is automatically doing a base64 encoding of that value
=> convert ClientSecret to string to avoid base64 encoding by json.Marshal
