IBM/ibm-iam-operator

deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
pkg/controller/authentication/containers.go
pkg/controller/secretwatcher/secretwatcher_controller.go

Related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36265

reflect recent chart changes into operator code and update image versions

---

pkg/controller/authentication/secret.go

Related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36162

auto generate credentials

---

pkg/controller/authentication/service.go

Because of catalog UI redirect problem it has to change container
port of management ingress from 8443 to 443.

Change management ingress container port to 443

---

deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
version/version.go

Updating csv and operator version based on https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37048

update operator and csv version

---

deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml

Resolved https://github.com/IBM/ibm-iam-operator/issues/37

remove the required field

---

deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml

Updated pap and iam-policy-controller image version for Q22020 release.

Updated pap and iam-policy-controller image version for Q22020 release.

---

pkg/controller/authentication/deployment.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/pap_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/policydecision_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go

Code change for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37112

Cr update --Do not merge

---

pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go

Resolved the intermittent issue with client CRD creation (Issue #37325)

Resolved the intermittent issue with client CRD creation (Issue #37325)

---

pkg/controller/authentication/webhook.go

Changed default TimeoutSeconds value to 10 (Issue #37658)

Changed default TimeoutSeconds value to 10 (Issue #37658)

---

pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/configmap.go
pkg/controller/authentication/secret.go

Code changes to reuse same clientid and secret values on reconcile (Issue #37868)

Code changes to reuse same clientid and secret values on reconcile (Issue #37868)

---

deploy/olm-catalog/ibm-iam-operator/3.6.2/ibm-iam-operator.v3.6.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38503

changing release tag to digest

---

Makefile
deploy/olm-catalog/ibm-iam-operator/3.6.3/ibm-iam-operator.v3.6.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_securityonboardings_crd.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml

_need to update the image tag for identity_provider in CSV and operator.yaml_

[DO NOT MERGE] adding files for 3.6.3 operator

---

deploy/olm-catalog/ibm-iam-operator/3.6.3/ibm-iam-operator.v3.6.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
deploy/operator.yaml

_**Waiting on Operator sha to promote to beta channel**_

promoting dev to beta

---

deploy/olm-catalog/ibm-iam-operator/3.6.4/ibm-iam-operator.v3.6.4.clusterserviceversion.yaml

Latest `platform-auth-service` and `platform-identity-manager` tags aren't in quay yet.

update operand tags

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39723

Update to use ubi8-minimal/8.2.339

---

pkg/controller/authentication/configmap.go

Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade.

Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade.

---

deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/39780

promote beta channel  to stable

---

pkg/controller/authentication/configmap.go

Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade for 3.6.4 branch.

Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade for 3.6.4 branch.

---

Makefile
common/scripts/config_docker.sh

Code changes to integrate images with the new CICD pipeline. (Issue #[40018](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40018))

Code changes to integrate images with the new CICD pipeline. (Issue #40018)

---

deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/authentication/deployment.go
pkg/controller/authentication/job.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/pap_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/policydecision_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go
pkg/controller/securityonboarding/securityonboarding_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38460

Remove product version

---

deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
pkg/controller/authentication/configmap.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39426

Update configmap to set roks parameters

---

deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
deploy/operator.yaml

Operands that required digest update:
- identity-manager
- identity-provider
- policy-administration
- secret-watcher

update operand shas

---

deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40265
New audit logging image for Beta 1

Update with new audit logging sha

---

deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for plaform-auth, identity-provider and identity-manager container images.

Updated latest image sha digest for plaform-auth, identity-provider and identity-manager container images.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for platform-auth and identity-provider container images for 3.7.1

Updated latest image sha digest for platform-auth and identity-provider container images for 3.7.1

---

deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml

Epic: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37751
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40673

adding support for power and z

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated new image sha digest for platform-auth, identity-provider and identity-manager container images.

Updated new image sha digest for platform-auth, identity-provider and identity-manager container images.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for IAM operand images.

Updated latest image sha digest for IAM operand images.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest sha digest for platform-auth and identity-provider images.

Updated latest sha digest for platform-auth and identity-provider images.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest sha digest for identity-manager image.

Updated latest sha digest for identity-manager image.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for oidcclient-watcher operand image.

Updated latest image sha digest for oidcclient-watcher operand image.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

identity-provider: https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/37991315#L286
identity-manager: https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/37990181#L304

Update identity-manager and identity-provider shas

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for identity-provider operand image.

Updated latest image sha digest for identity-provider operand image.

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/platform-identity-mgmt/pull/598
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/38017156#L306

updating sha for identity-manager

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

https://travis.ibm.com/IBMPrivateCloud/pap/jobs/38151937#L358

updating PAP sha

---

deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
deploy/operator.yaml

Reverts IBM/ibm-iam-operator#193
Will update the PAP image in new CSV version.

Revert "updating PAP sha"

---

deploy/olm-catalog/ibm-iam-operator/3.7.2/ibm-iam-operator.v3.7.2.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest sha digest for IAM operand identity-manager image.

Updated latest sha digest for IAM operand identity-manager image.

---

deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest sha digest for all IAM operand images.

Updated latest sha digest for all IAM operand images.

---

deploy/crds/operator.ibm.com_authentications_crd.yaml
deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_authentications_crd.yaml
pkg/apis/operator/v1alpha1/authentication_types.go
pkg/controller/authentication/ingress.go

Reverts IBM/ibm-iam-operator#205

Revert "Ready to merge: Accept x-frame domain value in operand configuration"

---

build/Dockerfile
build/Dockerfile.ppc64le

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41393
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41398

Update ubi image

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
version/version.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42133

4q CSV updates

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for IAM operands pap and iam-onboarding images.

Updated latest image sha digest for IAM operands pap and iam-onboarding images.

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.0/oidc_v1_client_crd.yaml

Related to github.ibm.com/IBMPrivateCloud/roadmap/issues/42292

resolve the errors in CRs related to audit

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for identity-manager.

Updated latest image sha digest for identity-manager.

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for identity-provider image.

Updated latest image sha digest for identity-provider image.

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

https://na.artifactory.swg-devops.com/ui/repos/tree/General/hyc-cloud-private-integration-docker-local%2Fibmcom%2Ficp-secret-watcher%2F3.3.6%2Flist.manifest.json
https://travis.ibm.com/IBMPrivateCloud/icp-secret-watcher/jobs/40907507

Update secret watcher sha

---

pkg/controller/authentication/service.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42351

Update service.go to update mgmt ingress port

---

deploy/crds/operator.ibm.com_authentications_crd.yaml
deploy/crds/operator.ibm.com_paps_crd.yaml
deploy/crds/operator.ibm.com_policydecisions_crd.yaml
pkg/apis/operator/v1alpha1/authentication_types.go
pkg/controller/authentication/containers.go
pkg/controller/authentication/deployment.go
pkg/controller/pap/containers.go
pkg/controller/pap/pap_controller.go
pkg/controller/policydecision/containers.go
pkg/controller/policydecision/policydecision_controller.go
pkg/resources/constants.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41447
Addressing upgrade scenario for new audit syslog sidecar.

Auditlogging upgrade

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml
deploy/role.yaml
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42260

inject pod namespace environment variable in oidc client watcher

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42260
Obtain the sha here https://travis.ibm.com/IBMPrivateCloud/icp-oidcclient-watcher/jobs/41045921

Update oidc client watcher sha

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/operator.yaml

Fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42039
Twistlock fix for PAP and auth-service

Update sha for identity-manager, pap and auth-service

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
pkg/apis/operator/v1alpha1/accesspolicies.go
pkg/controller/authentication/certificate.go
pkg/controller/authentication/webhook.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/securityonboarding/securityonboarding_controller.go

Related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42279

Remove namespace hardcoding

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

After fixing:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42492
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42552

Update iam onboarding image after ubi update

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated iam-policy-controller latest image sha digest.
Travis multi-arch build link:
https://travis.ibm.com/IBMPrivateCloud/iam-policy-controller/jobs/41491148#L272

Updated iam-policy-controller latest image sha digest.

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

policy decision: https://travis.ibm.com/IBMPrivateCloud/iam-policy-decision/jobs/41370121#L280
identity-mgmt: https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/41511346#L311

changing pdp and id-mgmt digests

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42755

update audit image

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Resolves 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42813
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42825
Travis multi-arch build links:
https://travis.ibm.com/IBMPrivateCloud/icp-oidcclient-watcher/jobs/41829240#L279
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/41834731#L315

udpated the sha of oidcclient-watcher

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Travis build multi-arch link for image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/42098179#L317

Update idmgmt errorcode

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image sha digest for iam-onboarding image.
Related issue:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42915
Travis multi-arch build link for latest image sha digest:
https://travis.ibm.com/IBMPrivateCloud/icp-iam-onboarding/jobs/42136123#L293

Updated latest image sha digest for iam-onboarding image.

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml

Related issue:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41364
Travis multi-arch build links for latest image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-auth-service/jobs/42140261#L295
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/42140248#L293
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/42140186#L313
https://travis.ibm.com/IBMPrivateCloud/pap/jobs/42140471#L374

update sha values and image version.

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.8.2/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/ibm-iam-operator.v3.8.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_securityonboardings_crd.yaml
deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
deploy/operator.yaml
pkg/controller/authentication/containers.go
pkg/controller/authentication/secret.go
version/version.go

Related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40725

fix to support fips

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Travis build links for multi-arch image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43001959#L293
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/43009576#L313
https://travis.ibm.com/IBMPrivateCloud/iam-policy-decision/jobs/42884009#L276
https://travis.ibm.com/IBMPrivateCloud/icp-secret-watcher/jobs/42885163#L269
https://travis.ibm.com/IBMPrivateCloud/icp-oidcclient-watcher/jobs/42885411#L269
https://travis.ibm.com/IBMPrivateCloud/iam-policy-controller/jobs/42885505#L273

update image version and shas

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image shas for IAM operand images.
Travis build links for multi-arch image digest shas:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43068213#L297
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/43068165#L317
https://travis.ibm.com/IBMPrivateCloud/iam-policy-decision/jobs/43070015#L278

Updated latest image shas for IAM operand images.

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest image digest sha for identity-manager.
Travis multi-arch build link for image digest sha:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/43173963#L321

Updated latest image digest sha for identity-manager.

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Travis multi-arch build links for latest image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43445539#L397
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/43173963#L319

Update img with cp4auto changes

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated identity-manager latest image sha digest.
Travis multi-arch build link for image sha digest:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-mgmt/jobs/43455084#L317

Updated identity-manager latest image sha digest.

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43534483#L327
Changes for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42971
IBMPrivateCloud/platform-identity-provider#344

Update sha kid - issue 42971

---

deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/authentication/deployment.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/pap_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/policydecision_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go

Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42860

remove deprecated labels

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

Fixes: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43397
Travis multi-arch build link for latest image digest sha:
https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43829712#L307

Cp4auto jwk changes, update operator image with these changes

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml

https://travis.ibm.com/IBMPrivateCloud/platform-identity-provider/jobs/43850251#L285

updating identity-provider sha

---

deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
deploy/operator.yaml

https://travis.ibm.com/IBMPrivateCloud/platform-auth-service/jobs/43764274 ( line :506 )
https://travis.ibm.com/IBMPrivateCloud/pap/jobs/43763998 ( line :726 )
https://travis.ibm.com/IBMPrivateCloud/icp-iam-onboarding/builds/43763697 ( line :473 )

sha value update for ibm-iam-operator EUS release

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/authentication/deployment.go
pkg/controller/authentication/job.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/pap_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/policydecision_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go
pkg/controller/securityonboarding/securityonboarding_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43292

Update with new name format

---

pkg/apis/operator/v1alpha1/accesspolicies.go
pkg/controller/authentication/clusterrole.go
pkg/controller/authentication/clusterrolebinding.go

Related issue:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43317

support cloudpak admin role

---

pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go

Related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44004

mount root ca certs

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44247

Add zen service id to bindinfo

---

pkg/controller/authentication/deployment.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/pap_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/policydecision_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go

Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44249

preserve cert manager label in pod spec

---

pkg/controller/authentication/clusterrole.go

Related issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44371

give cloudpak admin access to must gather

---

deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml

See -
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44331

Update bindinfo key to protected

---

Makefile

See issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44457

Update Makefile to use v1.0.3 version manifest tool

---

pkg/controller/authentication/constants.go

Resolved issue with scim mapping json.

Resolved issue with scim mapping json.

---

pkg/controller/authentication/constants.go

Changed SCIM default mapping of displayName to cn(full name).

Changed SCIM default mapping of displayName to cn(full name)

---

deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
deploy/role.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44579

Add permission to create delete rolebinding

---

deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
deploy/operator.yaml

Updated identity-manager version for 3.7.1 Fixpack release.

Updated identity-manager version for 3.7.1 Fixpack release.

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated identity-manager version for master.

Updated identity-manager version for master.

---

deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
deploy/operator.yaml

Updated provider and oidclient-watcher latest version for 3.7.1 Fixpack release.

Updated provider and oidclient-watcher latest version for 3.7.1 Fixpack release.

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml

to fix https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45374

Update replace version

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated pdp image latest version for master.

Updated pdp image latest version for master.

---

deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
deploy/operator.yaml

Updated pdp image latest version for EUS release branch.

Updated pdp image latest version for EUS release branch.

---

deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
deploy/operator.yaml

update version for operand after lodash fix in 3.9.2

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
deploy/operator.yaml

Fixes for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44850

update version with lodash fixes to master

---

deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml

To fix https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45501

Update version to 3.8.3 in csv

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated iam-onboarding image latest version for master branch.

Updated iam-onboarding image latest version for master branch.

---

OWNERS

Removed approver and reviewer permissions for Srinivas.

Update OWNERS - remove Srinivas from owners list

---

pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/secretwatcher/secretwatcher_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45625

preserve-annotation from nss operator

---

pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45722

Update oidcclient watcher to mount the certificates

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45939

Issue45939 - eus vulnerabilities

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45863

Issue45863 - vuln in operator master

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml

Fix for 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46117

remove bind/escalate verbs

---

deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated latest versions for operands for 2Q2021 release.

Updated latest versions for operands for 2Q2021 release

---

pkg/controller/authentication/containers.go
pkg/controller/authentication/deployment.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46388

check for saas tenant configmap and update deployment

---

pkg/controller/authentication/deployment.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46388

return err to requeue and wait for cm creation

---

pkg/controller/authentication/deployment.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45625

Update deployment.go - check nss annotations

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

Fix for twistlock issue:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46544

fix for issue 46544

---

pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/clusterrole.go
pkg/controller/authentication/clusterrolebinding.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/resources/utils.go

Code changes to handle uninstall of cluster resources in case of multiple instances of IAM (Related issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45718)

Code changes to handle uninstall of cluster resources in case of multiple instances of IAM (Issue #45718)

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_securityonboardings_crd.yaml
version/version.go

Update IBM IAM Operator to 3.11.0 for Common Services 3.9
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47644

update to 3.11.0 for common services 3.9 and cd pipeline

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_securityonboardings_crd.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47811
Use the new proposed way of updating master for Common Services 3.9 development

update operator version to 3.11.0

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/4.0.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_securityonboardings_crd.yaml
version/version.go

https://github.ibm.com/ibmprivatecloud/roadmap/issues/47811
Future pipeline for code not planned for Common Services 3.9

bump up iam future version 4.0.0

---

deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47316
Add minKubeVersion

Update minKubeVersion in csv

---

deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45068
Bump up operand versions for issue 45068 and 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47407

Update ibm-iam-operator.v3.11.0.clusterserviceversion.yaml to bump up operands

---

deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
deploy/crds/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48018

copy crds to olm-catalog

---

deploy/crds/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml

https://github.ibm.com/PrivateCloud-analytics/Zen/issues/26208

Preserve unknown fields

---

README.md

Updated for case bundle: 1.2.4 - Provide accurate and consumable steps to deploy in the README

Update README.md for case bundle

---

deploy/crds/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
pkg/apis/operator/v1alpha1/authentication_types.go
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/webhook.go

multiple deployments on-prem
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47395

Chun prem multiple

---

OWNERS
deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/platform-identity-provider/pull/428

Bumpup identity provider for issue 47429

---

deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48090

Bump up auth service version to 3.6.1 - after loopback removal

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x
common/config/.hadolint.yml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48536

opt in and use common ibm base images

---

deploy/operator.yaml

Update operator.yaml to increase request for ibm-iam-operator based one requestPred in Grafana UI
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48517

Update operator.yaml to increase request for ibm-iam-operator

---

Makefile

Fix for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47847

update build params

---

Makefile
common/Makefile.common.mk
common/config/.golangci.yml
common/scripts/lint-csv.sh
common/scripts/next-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.11.2/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/ibm-iam-operator.v3.11.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

Update to 3.11.2 and update operand versions

Automate next csv and update to 3.11.2, update operand versions.

---

deploy/olm-catalog/ibm-iam-operator/3.11.2/ibm-iam-operator.v3.11.2.clusterserviceversion.yaml

Reverts IBM/ibm-iam-operator#406

Revert "Update ibm-iam-operator.v3.11.2.clusterserviceversion.yaml"

---

common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/ibm-iam-operator.v4.0.0+k.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_securityonboardings_crd.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49608

update to 4.0.0+k for project k pipeline work 

---

deploy/olm-catalog/ibm-iam-operator/4.0.0-k/ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml

Update ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml to update replaces

---

pkg/controller/authentication/webhook.go

Update webhook.go to v1 review version again

---

deploy/olm-catalog/ibm-iam-operator/3.12.0/ibm-iam-operator.v3.12.0.clusterserviceversion.yaml
deploy/operator.yaml

Use updated versions for release-k

[release-k]-Update csv to use new operand image versions

---

pkg/apis/operator/v1alpha1/accesspolicies.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50480

Update accesspolicies.go to update print statement after moving to python3

---

pkg/apis/operator/v1alpha1/accesspolicies.go
pkg/controller/securityonboarding/securityonboarding_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50479

Issue50426-2

---

README.md

Update README.md to trigger new master build

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.8.5/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/ibm-iam-operator.v3.8.5.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

IAM operands and operator update

update to 3.6.6

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.12.2/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/ibm-iam-operator.v3.12.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

For [#50615](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50615)

Release lock after 3.13

---

deploy/olm-catalog/ibm-iam-operator/3.8.5/ibm-iam-operator.v3.8.5.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50103

Update ibm-iam-operator.v3.8.5.clusterserviceversion.yaml Added Image tags section for CICD automation

---

pkg/controller/authentication/webhook.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48833

Update webhook.go to remove v1beta1

---

pkg/apis/operator/v1alpha1/accesspolicies.go
pkg/controller/securityonboarding/securityonboarding_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50582

python3 upgrade

---

pkg/controller/authentication/configmap.go
pkg/controller/authentication/containers.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51077

Issue51077 - check global cpp configmap

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.8.6/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/ibm-iam-operator.v3.8.6.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51367

update from 3.8.5 to 3.8.6

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.16.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/ibm-iam-operator.v3.16.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.16.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51971

update from 3.13 to 3.16

---

pkg/controller/authentication/ingress.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52280
Implementing ingress for social login.

ingress for social login

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.18.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53123

update from 3.17 to 3.18

---

deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53123

removing replaces in operator

---

pkg/controller/authentication/ingress.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52825

do not expose loopback swagger endpoint

---

common/config/.hadolint.yml
deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml
deploy/operator.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53270

movement to icr

---

deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml

as per https://ibm-cloudplatform.slack.com/archives/G013X1K33AN/p1651811391592849

add back replaces:

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.19.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/ibm-iam-operator.v3.19.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53502

version bump for CS 3.19.0

---

deploy/olm-catalog/ibm-iam-operator/3.20.0/ibm-iam-operator.v3.20.0.clusterserviceversion.yaml

https://ibm-cloudplatform.slack.com/archives/G013X1K33AN/p1657561833006569

Remove replace from CD3.20

---

pkg/controller/authentication/configmap.go

issue : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54355

SCIM_AUTH_CACHE_MAX_SIZE Param - Upgrade handling

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.19.3/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/ibm-iam-operator.v3.19.3.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54397

version bump for 3.19.3 LTSR

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.21.0/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/ibm-iam-operator.v3.21.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.21.0/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54534

version bump for CS 3.21.0 release

---

pkg/controller/securityonboarding/securityonboarding_controller.go

Based on the discussion on PR - https://github.com/IBM/ibm-iam-operator/pull/488
This new PR has been raised with removal of capture the iam-onboarding logs
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53620
Change in brief -> Add init container to check two crucial endpoints before starting the actual job. The script to check endpoints is available in iam-onboarding job.

IAM onboarding resiliency

---

pkg/controller/securityonboarding/securityonboarding_controller.go

Based on the discussion on PR - https://github.com/IBM/ibm-iam-operator/pull/488
This new PR has been raised with removal of capture the iam-onboarding logs
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53620
Change in brief -> Add init container to check two crucial endpoints before starting the actual job. The script to check endpoints is available in iam-onboarding job.

IAM onboarding resiliency (#492)

---

pkg/controller/authentication/configmap.go
pkg/controller/authentication/constants.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55171

Handle console url for registration json based on port 443 #55171

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

add Client permissions to ibm-iam-operator role
remove Client and rolebinding permissions from ibm-iam-operand role

Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to add Client permissions to ibm-iam-operator role

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

Add volumeMount to deployment in CSV

---

pkg/controller/authentication/configmap.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55695

Remainder changes for splitting auth idp

---

README.md

Intention of this PR is to trigger a build on a prow machine that has updated go version

trigger build on prow that has updated go version

---

cmd/manager/main.go
deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56719
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56736

[Cloudpak 3.0] Made changes to support multiple namespace

---

cmd/manager/main.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56719
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56736

Added sigs.k8s.io/controller-runtime/pkg/cache package

---

Makefile
build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x
common/config/.hadolint.yml
common/scripts/config_docker.sh

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56853

Update artifactory - Release LTSR

---

Makefile
build/Dockerfile
build/Dockerfile.amd64
build/Dockerfile.ppc64le
build/Dockerfile.s390x
common/config/.hadolint.yml
common/scripts/config_docker.sh

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56853

Update artifactory - Release Future

---

pkg/apis/oidc/v1/client_types.go
pkg/controller/client/client_controller.go
pkg/controller/client/clientreg.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55959

Amend cpclient credentials

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

add intent: projected label
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56808

[CP 3.0] - Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to add label

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/sacc.go
pkg/resources/utils.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56668

osauth:update SA with annotation

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
pkg/apis/addtoscheme_operator_v1alpha1.go
pkg/apis/operator/v1alpha1/authentication_types.go
pkg/apis/operator/v1alpha1/register.go
pkg/controller/authentication/authentication_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56885

remove userbuilder

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/apis/addtoscheme_operator_v1alpha1.go
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/certificate.go
pkg/controller/authentication/configmap.go
pkg/controller/authentication/deployment.go
pkg/controller/authentication/ingress.go
pkg/controller/authentication/job.go
pkg/controller/authentication/routes.go
pkg/controller/authentication/secret.go
pkg/controller/authentication/service.go
pkg/controller/client/clientreg.go

Originating issue: [IBMPrivateCloud/roadmap#56314](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56314)

Replace Ingresses with Routes

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

Signed-off-by: Steve Grube <sgrube@us.ibm.com>

move route permissions to IAM operator SA

---

pkg/controller/authentication/containers.go
pkg/controller/authentication/deployment.go

Remove router-certs from auth deployment

---

pkg/controller/authentication/routes.go

Add route for social login

---

pkg/controller/authentication/routes.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57143

Update routes.go to fix idmgmt

---

pkg/controller/authentication/containers.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57010

provider and management pods to check for auth-service readiness

---

Makefile
deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
deploy/operator.yaml
deploy/role.yaml
deploy/role_binding.yaml
deploy/service_account.yaml
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/clusterrole.go
pkg/controller/authentication/clusterrolebinding.go
pkg/controller/authentication/routes.go
pkg/controller/authentication/sacc.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57090

sod changes

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
deploy/operator.yaml
go.mod
go.sum
pkg/controller/client/client_controller.go
pkg/controller/client/client_controller_config.go
pkg/controller/client/clientreg.go
pkg/controller/client/conditions.go
pkg/controller/client/iam.go
pkg/controller/client/icperror.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56869

Issue 56869

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.23.2/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/ibm-iam-operator.v3.23.2.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

3.19.10/3.23.2 version bump

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

- Replace auditService block in alm-examples with one matching our dummy data in Authentication CRs
- Replace quay image references with ICR ones
- Remove environment variables related to unused images

Clean up CSV

---

deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_authentications_crd.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57884

Add preserve unknown fields value to status subresource

---

pkg/controller/authentication/routes.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57859

[Cloud Pak 3.0] - SAML and OIDC HA login support

---

pkg/apis/apis.go
pkg/apis/certmanager/v1alpha1/certificate_common.go
pkg/apis/oidc/v1/client_types.go
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/certificate.go
pkg/controller/authentication/configmap.go
pkg/controller/authentication/deployment.go
pkg/controller/authentication/ingress.go
pkg/controller/authentication/job.go
pkg/controller/authentication/routes.go
pkg/controller/authentication/sacc.go
pkg/controller/authentication/secret.go
pkg/controller/authentication/service.go
pkg/controller/client/conditions.go
pkg/controller/controller.go
version/version.go

Originating issue: [IBMPrivateCloud/roadmap#57108](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57108)
- Add rate limits to all IAM Routes
- Fix constant reconcile loops that were triggered by failed Route
updates

Issue 57108

---

build/Dockerfile
build/Dockerfile.amd64
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58395

Changed IAM to IM in description and summary

---

pkg/apis/addtoscheme_operator_v1alpha1.go
pkg/apis/utils.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58183

Remove exit on failure for missing schemes

---

deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml

Originating issue: [IBMPrivateCloud/roadmap#58680](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680)

Update ImagePullPolicy to IfNotPresent

---

pkg/controller/authentication/routes.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58063

keep route certificate details

---

pkg/controller/authentication/routes.go

Originating issue: [IBMPrivateCloud/roadmap#59016](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59016)

Perform nil pointer check before dereference

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/4.1.0/ibm-iam-operator.v4.1.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/4.1.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.1.0/operator.ibm.com_authentications_crd.yaml
version/version.go

bump to 4.1.0

---

pkg/controller/authentication/configmap.go

Originating issue: [IBMPrivateCloud/roadmap#58977](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58977)

Correct cluster address for CNCF

---

deploy/olm-catalog/ibm-iam-operator/4.1.0/ibm-iam-operator.v4.1.0.clusterserviceversion.yaml

Replacement for https://github.com/IBM/ibm-iam-operator/pull/654

Rename MongoDB to IM-MongoDB

---

pkg/controller/authentication/ingress.go

Fixes -  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59023

fix for dynamic scan in LTSR

---

pkg/controller/authentication/ingress.go

Fixes - https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59023

fix for dynamic scan

---

pkg/controller/authentication/constants.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59560

fix permission issue

---

pkg/controller/authentication/constants.go

Reverts IBM/ibm-iam-operator#672
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59626

Revert "fix permission issue"

---

Makefile
deploy/olm-catalog/ibm-iam-operator/4.2.0/ibm-iam-operator.v4.2.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/4.2.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.2.0/operator.ibm.com_authentications_crd.yaml
deploy/operator.yaml
version/version.go

version bump for CS 4.2.0 release

version bump for CS 4.2.0

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.23.7/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/ibm-iam-operator.v3.23.7.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

ltsr(sept) version update

---

go.mod
go.sum

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59924

Updated github.com/emicklei/go-restful/v3 to v3.10.0

---

deploy/olm-catalog/ibm-iam-operator/3.23.7/ibm-iam-operator.v3.23.7.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/authentication/containers.go
pkg/controller/authentication/job.go
pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
pkg/controller/pap/containers.go
pkg/controller/policycontroller/policycontroller_controller.go
pkg/controller/policydecision/containers.go
pkg/controller/secretwatcher/secretwatcher_controller.go
pkg/controller/securityonboarding/securityonboarding_controller.go

Supporting imagePullPolicy as "IfNotPresent"

imagePull policy update

---

pkg/controller/authentication/ingress.go

Originating issue: [IBMPrivateCloud/roadmap#60186](https://github.ibm.com/ibmprivatecloud/roadmap/issues/60186)

Remove extra newline in Ingress config snippet

---

deploy/crds/oidc.security.ibm.com_clients_crd.yaml
deploy/crds/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.2.0/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/4.2.0/operator.ibm.com_authentications_crd.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59838

update CRD description for certification

---

deploy/operator.yaml
pkg/controller/authentication/containers.go

Issue : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60152

imagePull policy update for CD

---

deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
deploy/olm-catalog/ibm-iam-operator/4.3.0/ibm-iam-operator.v4.3.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/authentication/authentication_controller.go
pkg/controller/authentication/containers.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59638

ephemeral storage inclusion

---

pkg/controller/authentication/constants.go
pkg/controller/authentication/deployment.go
pkg/controller/authentication/job.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60841

fix for multi-arch issue

---

pkg/controller/authentication/deployment.go

Reverts IBM/ibm-iam-operator#694

Revert "Added ca cert for provider"

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.23.10/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/ibm-iam-operator.v3.23.10.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

LTSR DEC Version Bumpup

---

pkg/controller/client/client_controller.go

[Originating issue](https://github.ibm.com/ibmprivatecloud/roadmap/issues/60940)
Reconcile logic was missing returns for errors found during creates or
updates of Client CRs, which led to failing CRs never reconciling
properly unless retriggered with a small update.
Other changes:
* Remove vestigial CACHE_UPDATE check

Issue 60940

---

controllers/oidc.security/iam.go

Issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61877

Update iam.go to resolve pods crash issue

---

main.go

Originating issue: [IBMPrivateCloud/roadmap#61876](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61876)
* Use the default Cache in the Manager when in AllNamespaces mode.

Fix AllNamespaces mode

---

pkg/controller/authentication/configmap.go

Old PR https://github.com/IBM/ibm-iam-operator/pull/730
Issue https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61269

ldap-timeout-update

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.23.13/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/ibm-iam-operator.v3.23.13.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

3.23.13 ltsr version bump

---

controllers/operator/authentication_controller.go

Providing this PR as a means of backing out EDB schema initialization from the Operands if the images are not updated in time for the next build.

Disable DDL execution until Operands are updated

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
config/manager/bases/manager.yaml

Originating issue: [IBMPrivateCloud/roadmap#59790](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59790)

Add a common label for CPFS Operator Pods

---

controllers/operator/migration/v1.sql

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62500

scimattr schema change

---

apis/operator/v1alpha1/authentication_types.go
controllers/operator/operandrequest.go

Related to [IBMPrivateCloud/roadmap#62514](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62514)

Retain MongoDB if annotation is set on Auth CR

---

migration/schema/v1/dbinit.sql
migration/schema/v1/tables.go

originated from https://github.ibm.com/IBMPrivateCloud/roadmap/pull/62684

last_login column removal from users table

---

controllers/operator/authentication_controller.go
migration/migration.go

Originating issue: [IBMPrivateCloud/roadmap#62714](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62714)

Add handling for mongodb-preload-endpoint

---

migration/migration.go
migration/migration_test.go
migration/schema/v1/tables.go

Originating issue: [IBMPrivateCloud/roadmap#62740](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62740)

Set Zen instance client secret if not set

---

migration/schema/v1/dbinit.sql

Originating issue: [IBMPrivateCloud/roadmap#62777](https://github.ibm.com/IBMPrivateCloud/roadmap/pull/62777)

Create VIEWs for scim_server custom tables

---

migration/schema/v1/dbinit.sql

Originating issue: [IBMPrivateCloud/roadmap#62778](https://github.ibm.com/IBMPrivateCloud/roadmap/pull/62778)

ON DELETE CASCADE for user_preferences

---

migration/migration.go
migration/schema/v1/tables.go

related to https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62411
- Fetches the mongo data from `ScimServerUsers` and `ScimServerGroups` collections
- `ScimServerUsers` data is stored into `scim_server_users` and `scim_server_users_custom` tables
-  `ScimServerGroups` data is stored into `scim_server_groups` and `scim_server_groups_custom` tables

scimserver migration

---

controllers/operator/deployment.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62874

add bindinfoRefresh labels and annotations

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
hack/relatedimages.yaml
version/version.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63177

Update to version 4.6

---

DEVELOPMENT.md
README.md
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
hack/relatedimages.yaml
version/version.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63177.

Update to version 4.5.1

---

DEVELOPMENT.md
README.md
common/scripts/multiarch_image.sh

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63177

updating files v4.6

---

controllers/operator/containers.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63263

Refactoring memory utilisation

---

controllers/operator/authentication_controller.go
migration/migration.go
migration/options.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62995

Namespaced migration keys sc2

---

controllers/operator/operandrequest.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62243

Setting OwnerReference

---

migration/migration.go
migration/schema/v1/tables.go

Summary of changes:
1. Tokens from MongoDB collection being Migrated to EDB

Issue-63377: Migrating tokens to EDB

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63174

add zenFrontDoor flag to alm examples

---

Makefile
common/scripts/lint-csv.sh
deploy/olm-catalog/ibm-iam-operator/3.23.14/iam.policies_v1alpha1_iampolicy.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/ibm-iam-operator.v3.23.14.clusterserviceversion.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/oidc_v1_client_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_authentications_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_oidcclientwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_paps_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_policycontrollers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_policydecisions_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_secretwatchers_crd.yaml
deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_securityonboardings_crd.yaml
deploy/operator.yaml
version/version.go

LTSR June 3.23.14 version update

LTSR June 3.23.14 version update

---

controllers/operator/configmap.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63405

set endpoint address from cluster address on eks

---

controllers/operator/configmap.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63405

set endpoint address from cluster address on eks [ DONT MERGE - track 63424 ]

---

controllers/operator/authentication_controller.go
migration/migration.go
migration/options.go

This is port from SC2 PR https://github.com/IBM/ibm-iam-operator/pull/813 to CD

[CD]Namespaced migration keys

---

migration/migration.go
migration/schema/v1/tables.go

Porting changes from https://github.com/IBM/ibm-iam-operator/pull/819 to CD

[CD]Migrating tokens to EDB

---

controllers/oidc.security/client_controller.go

Issue => https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52227
Manual Test : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52227#issuecomment-80583945
Regression : Pending

[SC2] Update zen-instance for client CR update

---

controllers/operator/configmap.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63512#issuecomment-81303278

keep default mode as require

---

controllers/operator/authentication_controller.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63800
Testing done -

[SC2] Fix for Issue #63800: In-place upgrade from LTSR to 4.6.3 causing AuthenticationCR as NotReady

---

controllers/operator/configmap.go

This is port from sc2 to CD
that addresses: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62929

[CD]ensure roks_url is correct

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
config/manager/bases/manager.yaml
controllers/common/constants.go
controllers/operator/authentication_controller.go

This is back-port from sc2 release
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63130

[CD]shutdown mongo on successful migration

---

Dockerfile
build/Dockerfile.amd64
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64200

Updated to ubi9 [SC2]

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/bases/manager.yaml
controllers/operator/containers.go
controllers/operator/deployment.go
controllers/operator/job.go

Addressing Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64462

Adding securityContext field

---

Dockerfile
build/Dockerfile.amd64
build/Dockerfile.ppc64le
build/Dockerfile.s390x

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64200

Updated to ubi9 [CD]

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
config/manager/bases/manager.yaml
controllers/operator/containers.go
controllers/operator/deployment.go
controllers/operator/job.go

Addressing Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64462

Adding field SecurityContext

---

controllers/operator/deployment.go

Originating issue: [IBMPrivateCloud/roadmap#59800](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59800)

Added ca crt in provider secret [CD]

---

controllers/operator/containers.go

Reverts IBM/ibm-iam-operator#872

Revert "sleep introduce for init container"

---

apis/zen.cpd.ibm.com/v1/zenextension_types.go
controllers/operator/resourcestatus.go

* Add ZenExtension to and remove Routes from ServiceStatus when front door is enabled

Update aggregated status checks for ZenExtension

---

controllers/operator/deployment.go

Porting back - https://github.com/IBM/ibm-iam-operator/pull/853
quay.io/shyr_mei_yang1/ibm-iam-operator:cacrtsc2

Added ca crt in provider secret

---

.gitignore
DEVELOPMENT.md
Makefile
common/scripts/multiarch_image.sh
hack/bundle-render
hack/channel-render

* Adds support for building an FBC locally for dev purposes
* Include a step-by-step guide on how to create such a catalog

Add catalog building

---

DEVELOPMENT.md
README.md
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
hack/relatedimages.yaml
version/version.go

version bump up for iam-op Dec/4.6.9 sc2

4.6.9 sc2 bumpup

---

controllers/common/utils.go
controllers/operator/deployment.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65178

[SC2]fix for bindinfoRefresh

---

config/prometheus/monitor.yaml
database/connectors/options.go
database/migration/migration.go

quay.io/rani_prathyusha_elaprolu/ibm-iam-operator:tlstestiamop
Originating Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64854

Set InsecureSkipVerify to false[CD]

---

controllers/operator/authentication_controller.go

Originating issue: [PrivateCloud-analytics/CPD-Quality#34291](https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/34291)

Watch ibm-cpp-config and product-configmap

---

controllers/operator/configmap.go
controllers/operator/configmap_test.go

Originating issue: [PrivateCloud-analytics/CPD-Quality#38918](https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/38918)

Always add cluster_address_auth for Zen

---

controllers/operator/authentication_controller.go

Originating issue: [IBMPrivateCloud/roadmap#65763](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65763)

Handle being up with CM and no Authentication

---

controllers/operator/configmap.go

Originating issue: [IBMPrivateCloud/roadmap#65766](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65766)

Only configure OS Auth when on OCP

---

controllers/operator/deployment.go
controllers/operator/job.go
helm-cluster-scoped/Chart.yaml
helm-cluster-scoped/templates/clusterrole.yaml
helm-cluster-scoped/templates/clusterrolebinding.yaml
helm-cluster-scoped/templates/oidc.security.ibm.com_clients.yaml
helm-cluster-scoped/templates/operator.ibm.com_authentications.yaml
helm/Chart.yaml
helm/templates/00-serviceaccount.yaml
helm/templates/01-role.yaml
helm/templates/02-rolebinding.yaml
helm/templates/10-deployment.yaml
helm/values.yaml

Originating issues:
* [IBMPrivateCloud/roadmap#65065](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65065)
Add Helm chart for deploying the IM Operator

[CD] Add nonOLM support

---

Makefile
apis/operator/v1alpha1/authentication_types.go
apis/operator/v1alpha1/groupversion_info.go
apis/operator/v1alpha1/operandrequest_types.go
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_authentications.yaml
controllers/common/utils.go
controllers/operator/authentication_controller.go
controllers/operator/clusterrole.go
controllers/operator/clusterrolebinding.go
controllers/operator/configmap.go
controllers/operator/operandrequest.go
controllers/operator/resourcestatus.go
controllers/operator/routes.go
controllers/operator/zenextension.go
go.mod
main.go

Originating issue: [IBMPrivateCloud/roadmap#65337](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65337)
* Allows for gracefully skipping tasks that would require cluster permissions
* Improves handling around missing API resource support in cluster

[CD] Remove mandatory cluster-scoped permissions

---

helm-cluster-scoped/Chart.yaml
helm/Chart.yaml

Update Chart.yaml version to match appVersion

Update Chart.yaml to match appVersion

---

DEVELOPMENT.md
README.md
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
hack/relatedimages.yaml
version/version.go

version bump for mar/2025/sc2

---

helm/templates/02-rolebinding.yaml

Fixes : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65856

create operator rolebinging in operator namespace

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
helm-cluster-scoped/templates/clusterrole.yaml
helm-cluster-scoped/templates/clusterrolebinding.yaml
helm-cluster-scoped/templates/oidc.security.ibm.com_clients.yaml
helm-cluster-scoped/templates/operator.ibm.com_authentications.yaml
helm/templates/00-serviceaccount.yaml
helm/templates/01-role.yaml
helm/templates/02-rolebinding.yaml
helm/templates/10-deployment.yaml
helm/values.yaml
version/version.go

add component id

---

controllers/operator/migration.go

Originating issue: [IBMPrivateCloud/roadmap#65879](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65879)
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65907

[CD] Skip MongoDB bootstrap CM update when not present

---

controllers/operator/migration.go

Originating issue: [IBMPrivateCloud/roadmap#65879](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65879)

[SC2] Skip MongoDB bootstrap CM update when not present

---

helm/templates/10-deployment.yaml

Missed this change to update the deployment using the values under cpfs for imageRegistryNamespaceOperator and imageRegistryNamespaceOperand

Update 10-deployment.yaml to add cpfs prefix

---

controllers/operator/migration.go

Fixes:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65916

AllNamespace upgrade- check mongo deployment in instance namespace

---

controllers/operator/migration.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65916

[sc2]AllNamespace upgrade- check mongo deployment in instance namespace

---

helm/templates/00-rbac.yaml
helm/templates/10-deployment.yaml
helm/values.yaml

Originating issue: [IBMPrivateCloud/roadmap#66103](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66103)

Support adding custom labels to chart resources

---

Makefile

Update envtest version using latest kubebuilder guidance.

[SC2] Update envtest automatically

---

Makefile

Update envtest version using latest kubebuilder guidance.

[CD] Update envtest automatically

---

controllers/operator/certificate.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65836

add manage-cert-rotation label to certificates

---

controllers/operator/operandrequest.go

Originating issue: [IBMPrivateCloud/roadmap#66197](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66197)

Set Controller on im-common-service

---

controllers/oidc.security/client_controller.go
controllers/oidc.security/client_controller_config.go
controllers/operator/authentication_controller.go
controllers/operator/operandrequest_test.go
controllers/operator/secret.go
main.go

Originating issue: [IBMPrivateCloud/roadmap#66250](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66250)

[sc2]Get from API server when cache fails

---

DEVELOPMENT.md
README.md
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
database/schema/v1/tables_test.go
hack/relatedimages.yaml
helm-cluster-scoped/Chart.yaml
helm/Chart.yaml
helm/templates/10-deployment.yaml
helm/values.yaml
version/version.go

Version bump June CD [ 4.13 ]

---

controllers/operator/authentication_controller.go

Originating issue: [IBMPrivateCloud/roadmap#66568](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66568)

Shift migration earlier in Auth reconcile

---

controllers/operator/authentication_controller.go
controllers/operator/deployment.go
controllers/operator/resourcestatus.go

Originating issue: [IBMPrivateCloud/roadmap#66484](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66484)
* Simplify to one deferred function that writes out status changes to the Authentication CR

Rework Authentication status writes

---

DEVELOPMENT.md
README.md
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
common/scripts/multiarch_image.sh
config/manager/overlays/prod/image_env_vars_patch.yaml
config/manager/overlays/prod/kustomization.yaml
config/manifests/overlays/prod/annotations_patch.yaml
config/samples/overlays/prod/authentication_image_patch.yaml
hack/relatedimages.yaml
version/version.go

June SC2 Version Bump - 4.5.13

June SC2(4.6.15) Version Bump

---

controllers/operator/certificate.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66510

update certificates with manage-cert-rotation: true label

---

controllers/common/secondary.go

Originating issue: [IBMPrivateCloud/roadmap#66707](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66707)

Undo unstructured updates in Reconcile

---

controllers/bootstrap/authentication_bootstrap_controller.go
controllers/common/constants.go
controllers/common/utils.go
controllers/oidc.security/client_controller.go
controllers/oidc.security/client_controller_config.go
controllers/oidc.security/clientreg.go
controllers/operator/authentication_controller.go
controllers/operator/configmap.go
controllers/operator/resourcestatus.go
main.go

Originating issue: [IBMPrivateCloud/roadmap#66581](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66581)

Protect platform-auth-idp from upgrade clobber

---

controllers/operator/hpa.go

Fixes : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66740

updateHPA when profile size change

---

controllers/operator/hpa.go

addresses : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66810

minReplicas set to 2 for large profile

---

internal/controller/operator/containers.go
internal/controller/operator/deployment.go
internal/controller/operator/migration.go
internal/database/connectors/dbconn.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67117

[67117] Changes to connect to EDB using password

---

internal/controller/operator/secret.go

Originating issue: [PrivateCloud-analytics/Zen#42927](https://github.ibm.com/PrivateCloud-analytics/Zen/issues/42927)

Rollout Deploys on platform-oidc-credentials update

---

internal/controller/operator/job.go

fixes : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67782

fix volumeMount.Name not found issue +mongo secret name correction

---

internal/controller/operator/configmap.go
internal/controller/operator/job.go
internal/controller/operator/resourcestatus.go

Originating issue: [IBMPrivateCloud/roadmap#67779](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67779)

Use force deletion for Job cleanup

---

api/operator/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
internal/controller/operator/job.go

Originating issue: [IBMPrivateCloud/roadmap#67947](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67947)

RO root fs true for oidc-client-registration

---

bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
internal/controller/operator/containers.go

Revert PR to update the provider readiness probe as it was earlier.
OG PR - https://github.com/IBM/ibm-iam-operator/pull/1111/files#diff-fe748c338152d900611a26028af0cde87508c6bda3da8d60b4d0728356535ce2

Revert provider readiness probe

---

internal/controller/operator/configmap.go
internal/controller/operator/job.go

Originating issue: [IBMPrivateCloud/roadmap#67981](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67981)

Remove im-has-saml on rc > 1
